input:
    input.go: |
        package structs

        // goverter:converter
        // goverter:useZeroValueOnPointerInconsistency 1 2
        type Converter interface {
            Convert(Input) Output
        }

        type Input struct { Name string }
        type Output struct { Name string }
error: |-
    error parsing 'goverter:useZeroValueOnPointerInconsistency' at
        @workdir/input.go:5
        github.com/jmattheis/goverter/execution.Converter

    invalid value: expected one value but got 2: [1 2]
