name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.22.x
      - uses: actions/checkout@v3
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.2
      - run: go build ./cmd/goverter
      - run: go test -coverpkg ./...  -coverprofile=coverage.txt -covermode=atomic ./...
      - uses: codecov/codecov-action@v3
  'build_go118':
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      - uses: actions/checkout@v3
      - run: go build ./cmd/goverter
      - run: go test ./...
        env:
          SKIP_VERSION_DEPENDENT: 'true'
  build_docs:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: docs/yarn.lock
      - working-directory: docs
        run: |
          yarn install --frozen-lockfile
          yarn docs:build
